importing libraries

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [10]:
final_df=pd.read_csv(r"final_dataframe.csv")
final_df

,inning,cum_runs,cum_wickets,batting_team_encoded,bowling_team_encoded,venue_encoded,win
0,1,1,0,5,13,23,1
1,1,1,0,5,13,23,1
2,1,2,0,5,13,23,1
3,1,2,0,5,13,23,1
4,1,2,0,5,13,23,1
...,...,...,...,...,...,...,...
260915,2,110,2,5,15,28,1
260916,2,111,2,5,15,28,1
260917,2,112,2,5,15,28,1
260918,2,113,2,5,15,28,1


training and testing the dataframe

In [12]:
X = final_df.drop('win', axis=1)
Y = final_df['win']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print("traning and testing done successfully")

traning and testing done successfully


evaluating the models

importing libraries for models 

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

logistic regression 

In [14]:
print("training and testing for logistic regression")
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train,Y_train)
Y_train_pred=logistic_regression.predict(X_train)
Y_test_pred=logistic_regression.predict(X_test)
print("done successfully")
print("=======================================================")
print("performance on training data\n")
print("=======================================================")
print("accuracy:", accuracy_score(Y_train, Y_train_pred))
print("-------------------------------------------------------")
print("classification report:\n", classification_report(Y_train, Y_train_pred))
print("-------------------------------------------------------")
print("confusion matrix:\n", confusion_matrix(Y_train, Y_train_pred))
print("=======================================================")
print("performance on test data\n")
print("=======================================================")
print("accuracy:", accuracy_score(Y_test, Y_test_pred))
print("-------------------------------------------------------")
print("classification report:\n", classification_report(Y_test, Y_test_pred))
print("-------------------------------------------------------")
print("confusion matrix:\n", confusion_matrix(Y_test, Y_test_pred))

training and testing for logistic regression
done successfully
performance on training data

accuracy: 0.6461032117124023
-------------------------------------------------------
classification report:
               precision    recall  f1-score   support

           0       0.66      0.65      0.65    106713
           1       0.64      0.65      0.64    102023

    accuracy                           0.65    208736
   macro avg       0.65      0.65      0.65    208736
weighted avg       0.65      0.65      0.65    208736

-------------------------------------------------------
confusion matrix:
 [[68924 37789]
 [36082 65941]]
performance on test data

accuracy: 0.6480147171546834
-------------------------------------------------------
classification report:
               precision    recall  f1-score   support

           0       0.66      0.65      0.65     26722
           1       0.64      0.65      0.64     25462

    accuracy                           0.65     52184
   macro avg

random forest

In [15]:
print("training and testing for random forest")
random_forest = RandomForestClassifier()
random_forest.fit(X_train,Y_train)
Y_train_pred=random_forest.predict(X_train)
Y_test_pred=random_forest.predict(X_test)
print("done successfully")
print("=======================================================")
print("performance on training data\n")
print("=======================================================")
print("accuracy:", accuracy_score(Y_train, Y_train_pred))
print("-------------------------------------------------------")
print("classification report:\n", classification_report(Y_train, Y_train_pred))
print("-------------------------------------------------------")
print("confusion matrix:\n", confusion_matrix(Y_train, Y_train_pred))
print("=======================================================")
print("performance on test data\n")
print("=======================================================")
print("accuracy:", accuracy_score(Y_test, Y_test_pred))
print("-------------------------------------------------------")
print("classification report:\n", classification_report(Y_test, Y_test_pred))
print("-------------------------------------------------------")
print("confusion matrix:\n", confusion_matrix(Y_test, Y_test_pred))

training and testing for random forest
done successfully
performance on training data

accuracy: 0.9793231641882569
-------------------------------------------------------
classification report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98    106713
           1       0.98      0.98      0.98    102023

    accuracy                           0.98    208736
   macro avg       0.98      0.98      0.98    208736
weighted avg       0.98      0.98      0.98    208736

-------------------------------------------------------
confusion matrix:
 [[104531   2182]
 [  2134  99889]]
performance on test data

accuracy: 0.9477426030967346
-------------------------------------------------------
classification report:
               precision    recall  f1-score   support

           0       0.95      0.95      0.95     26722
           1       0.95      0.95      0.95     25462

    accuracy                           0.95     52184
   macro avg  

In [16]:
print("training and testing for XGBoost")
xgboost = XGBClassifier()
xgboost.fit(X_train,Y_train)
Y_train_pred=xgboost.predict(X_train)
Y_test_pred=xgboost.predict(X_test)
print("done successfully")
print("=======================================================")
print("performance on training data\n")
print("=======================================================")
print("accuracy:", accuracy_score(Y_train, Y_train_pred))
print("-------------------------------------------------------")
print("classification report:\n", classification_report(Y_train, Y_train_pred))
print("-------------------------------------------------------")
print("confusion matrix:\n", confusion_matrix(Y_train, Y_train_pred))
print("=======================================================")
print("performance on test data\n")
print("=======================================================")
print("accuracy:", accuracy_score(Y_test, Y_test_pred))
print("-------------------------------------------------------")
print("classification report:\n", classification_report(Y_test, Y_test_pred))
print("-------------------------------------------------------")
print("confusion matrix:\n", confusion_matrix(Y_test, Y_test_pred))

training and testing for XGBoost
done successfully
performance on training data

accuracy: 0.8749185574122337
-------------------------------------------------------
classification report:
               precision    recall  f1-score   support

           0       0.88      0.87      0.88    106713
           1       0.87      0.88      0.87    102023

    accuracy                           0.87    208736
   macro avg       0.87      0.87      0.87    208736
weighted avg       0.87      0.87      0.87    208736

-------------------------------------------------------
confusion matrix:
 [[93197 13516]
 [12593 89430]]
performance on test data

accuracy: 0.8711099187490419
-------------------------------------------------------
classification report:
               precision    recall  f1-score   support

           0       0.88      0.87      0.87     26722
           1       0.87      0.87      0.87     25462

    accuracy                           0.87     52184
   macro avg       0.87 